### ISSUE TITLE
关于wechat_articles

### ISSUE THREAD

**Issue by cd-cml** [alihanniba/wechat_articles_spider#1]
现在好像使用https://mp.weixin.qq.com/mp/getmasssendmsg?__biz=MzA3NzA0NTIzNw==&uin=MjE0NDEwNzY0MA%3D%3D&key=094f37d261b4da08f2f65d47b03cc98ee84477ab53bf97fd9d422f9369c7d793eb7ca9a243a943b605b820083ea914b9de67898e9c61a2f24069c781b68e3e063aa31c849b6d8d3a21b312ec96b693f2&f=json&frommsgid=1000000297&count=10
带上cookie已经不能返回json了，这个程序现在还能运行么

**Comment by Alihanniba** [comment]
每次抓包拿到的都只是临时地址，临时地址有效时间大概在30分钟以内，所以历史文章的地址需要你自己去抓包。我的这个地址已经失效了。

**Comment by cd-cml** [comment]
上门的地址就是我用抓包的地址拼的，但是始终不能返回json，不晓得哪个步骤出了问题？你现在运行这段程序能成功么，因为我觉得会不会微信又把机制改了

**Comment by Alihanniba** [comment]
你试试拿第二页的链接 直接去请求，看看会不会返回json, 晚上我回去看看

**Comment by Alihanniba** [comment]
目前我也没有权限拿到页面内容了，还需要继续研究
